apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    objectset.rio.cattle.io/hash: f09057d85bdfc1d6cb324ac990f4db2b567a9780
  name: elastic-searchllog
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-pv-claim
    namespace: elastic
  hostPath:
    path: /data/elasticsearch
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-claim
  namespace: elastic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeMode: Filesystem  
  volumeName: elastic-searchllog
  resources:
    requests:
      storage: 5Gi