apiVersion: v1
kind: Service
metadata:
  labels:
    objectset.rio.cattle.io/hash: 12002fe8f08460f0f3392a6df579037821d77810
  name: elasticsearch-np
spec:
  ports:
    - port: 9200
      nodePort: 31000
      protocol: TCP
      targetPort: 9200
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
