apiVersion: v1
kind: Service
metadata:
  labels:
    objectset.rio.cattle.io/hash: 9af6b43a03d096e389daf31d16f3a6a8cc40025c
  name: elasticsearch
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: ClusterIP
