apiVersion: v1
kind: Service
metadata:
  labels:
    objectset.rio.cattle.io/hash: c76755e990aeec02a912850aaa76bdd83461a1d5
  name: kibana
spec:
  ports:
    - port: 5601
      protocol: TCP
      nodePort: 31002
      targetPort: 5601
  selector:
    app: kibana
  sessionAffinity: None
  type: NodePort
