apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: senhub-prod
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: mariadb
      port: 3306
      protocol: TCP
      targetPort: 3306
  sessionAffinity: None
  type: ClusterIP
