apiVersion: v1
kind: Service
metadata:
  labels:
    objectset.rio.cattle.io/hash: 5f481c4938efab5f935ed01d93de8a88435080ee
  name: mariadb-np
  namespace: senhub-prod
spec:
  ports:
    - name: mariadb-np
      nodePort: 32306
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb
  sessionAffinity: None
  type: NodePort
